name: 'github-account-info-2-readme'
description: GitHub Action that retrieves user information, such as public data and repositories, and inserts it into a README file.
author: kotorkovsciy
branding:
  icon: user
  color: black

inputs:
  github_username:
    description: 'GitHub username'
    required: true
  target_file:
    description: 'The README file to update'
    required: true
  GH_TOKEN:
    description: 'GitHub access token with Repo scope'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get latest project
      shell: bash
      id: fetch_event
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        latest_project=$(
          ${{ github.action_path }}/scripts/get_latest_repo.sh \
          "${{ inputs.github_username }}"
        )

        echo "latest_project=$latest_project" >> $GITHUB_ENV

    - name: Update latest project in README
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/replace_between_tags.sh \
          "${{ github.workspace }}/${{ inputs.target_file }}" \
          "${{ env.latest_project }}" \
          "LAST_REPO"

    - name: Commit and push
      shell: bash
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        git add ${{ github.workspace }}/${{ inputs.target_file }}
        
        if git diff --cached --quiet; then
          echo "No changes detected, skipping commit and push."
        else
          git commit -m "Update README"
          git push
        fi

      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
